{% set name = "perl-file-slurp" %}
{% set version = "9999.28" %}
{% set sha256 = "0587ce010bcb79db9e744f14b5498be97bf2c7f2474d971916d92f0a10827cee" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/C/CA/CAPOEIRAB/File-Slurp-9999.28.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  host:
    - perl
    - perl-carp
    - perl-exporter

  run:
    - perl
    - perl-carp
    - perl-exporter

test:
  imports:
    - File::Slurp

about:
  home: http://metacpan.org/pod/File::Slurp
  license: perl_5
  summary: 'Simple and Efficient Reading/Writing/Modifying of Complete Files'
