{% set version = "0.19.6" %}

package:
  name: python-bioext
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/b0/a7/fd8fc1a710af2f5e5f97e4e852aad9ec27f0a830082f1347ef13929a9d2f/bioext-{{ version }}.tar.gz
  sha256: 8912dc470c2dd73bc634f73860d48025d8f4a7d6b715a965b4a73f87df4b47f1

build:
  number: 0
  skip: True # [py27]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cython
    - pip
    - numpy >=1.14.0
    - biopython >=1.58
  run:
    - python
    - biopython >=1.58
    - numpy >=1.14.0
    - scipy >=0.15
    - pysam >=0.9
    - six
    - joblib
    - freetype

test:
  imports:
    - BioExt
    - BioExt.align
    - BioExt.args
    - BioExt.collections
    - BioExt.errorize
    - BioExt.freetype
    - BioExt.freetype.ft_enums
    - BioExt.io
    - BioExt.io.BamIO
    - BioExt.io.LazyAlignIO
    - BioExt.io.SamIO
    - BioExt.joblib
    - BioExt.joblib.test
    - BioExt.merge
    - BioExt.misc
    - BioExt.ndarray
    - BioExt.optimize
    - BioExt.orflist
    - BioExt.phylo
    - BioExt.quiver
    - BioExt.rateclass
    - BioExt.references
    - BioExt.scorematrices
    - BioExt.stats
    - BioExt.uds
    - BioExt.untranslate

  commands:
    - bam2fna 2>&1 | grep 'usage' > /dev/null
    - bam2msa 2>&1 | grep 'usage' > /dev/null
    - bealign 2>&1 | grep 'usage' > /dev/null
    - clipedge 2>&1 | grep 'usage' > /dev/null
    - consensus 2>&1 | grep 'usage' > /dev/null
    - msa2bam 2>&1 | grep 'usage' > /dev/null
    - seqmerge 2>&1 | grep 'usage' > /dev/null

about:
  home: https://github.com/veg/BioExt.git
  license: GPL-3
  summary: 'A few handy bioinformatics tools not already in BioPython'
