package:
  name: perl-apache-test
  version: "1.42"

build:
  number: 0

source:
  url: https://cpan.metacpan.org/authors/id/S/SH/SHAY/Apache-Test-1.42.tar.gz
  sha256: 0681f07d7d8a9429d0edf8a8c5ad6a655be7fe81ada142670b2b8e776b3bb3eb

requirements:
  host:
    - perl
    - perl-pathtools
    - perl-extutils-makemaker

  run:
    - perl
    - perl-pathtools

test:
  imports:
    - Apache::Test

about:
  home: http://metacpan.org/pod/Apache::Test
  license: unknown
  summary: 'Special Tests Sequence Failure Finder'
