{% set name = "sequencetools" %}
{% set version = "1.4.0" %}
{% set sha256 = "9d96d380cab7b21a778be227cb5e0916726fb0f847ab8a753530c79172ff48bd" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/stschiff/sequenceTools/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  #  [osx]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - stack >=1.7.1
    - zlib
    - wget
    - gmp
    - perl 
    - xz
  run:
    - zlib
    - xz
    - gmp
    - samtools



test:
  commands:
    - pileupCaller --version

about:
  home: https://github.com/stschiff/sequenceTools
  license: MIT
  summary: Tools for population genetics on sequencing datas
