package:
  name: perl-http-daemon
  version: "6.06"

source:
  url: https://cpan.metacpan.org/authors/id/O/OA/OALDERS/HTTP-Daemon-6.06.tar.gz
  sha256: fc03a161b54553f766457a4267e7066767f54ad01cacfe9a91d7caa2a0319bad

build:
  number: 0
  noarch: generic

requirements:
  host:
    - perl
    - perl-http-date
    - perl-http-message
    - perl-lwp-mediatypes

  run:
    - perl
    - perl-http-date
    - perl-http-message
    - perl-lwp-mediatypes

test:
  # Perl 'use' tests
  imports:
    - HTTP::Daemon

about:
  home: http://metacpan.org/pod/HTTP-Daemon
  license: perl_5
  summary: 'a simple http server class'
