package:
  name: perl-http-daemon
  version: "6.05"

source:
  url: https://cpan.metacpan.org/authors/id/E/ET/ETHER/HTTP-Daemon-6.05.tar.gz
  sha256: b47fa46688bfd8a6e99eccf449dc5705e5530022b2fc8a873a9d07921345c72d

build:
  number: 0
  noarch: generic

requirements:
  host:
    - perl
    - perl-http-date
    - perl-http-message
    - perl-lwp-mediatypes

  run:
    - perl
    - perl-http-date
    - perl-http-message
    - perl-lwp-mediatypes

test:
  # Perl 'use' tests
  imports:
    - HTTP::Daemon

about:
  home: http://metacpan.org/pod/HTTP-Daemon
  license: perl_5
  summary: 'a simple http server class'
