
{% set name = "perl-mce-shared" %}
{% set version = "1.862" %}
{% set sha256 = "51949e8ed3b00dc9902c24fe60e6b001359af7eabf3ccfdc2247035423adc72b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/M/MA/MARIOROY/MCE-Shared-1.862.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  host:
    - perl
    - perl-socket
    - perl-constant
    - perl-storable
    - perl-mce >=1.836
    - perl-carp
    - perl-base
    - perl-time-hires
    - perl-extutils-makemaker
    - perl-test-simple

  run:
    - perl
    - perl-socket
    - perl-constant
    - perl-storable
    - perl-mce >=1.836
    - perl-carp
    - perl-base
    - perl-time-hires

test:
  imports:
    - MCE::Hobo
    - MCE::Shared
    - MCE::Shared::Array
    - MCE::Shared::Base
    - MCE::Shared::Cache
    - MCE::Shared::Condvar
    - MCE::Shared::Handle
    - MCE::Shared::Hash
    - MCE::Shared::Minidb
    - MCE::Shared::Ordhash
    - MCE::Shared::Queue
    - MCE::Shared::Scalar
    - MCE::Shared::Sequence
    - MCE::Shared::Server

about:
  home: https://github.com/marioroy/mce-shared
  license: perl_5
  summary: 'MCE extension for sharing data supporting threads and processes'

