{% set name = "pybel" %}
{% set version = "0.13.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "469201a25e77ab2f1519bd36847ca47b061c57243a084e07ea6e69bf0ff1acd6"

build:
  number: 0
  noarch: python
  entry_points:
    - pybel = pybel.cli:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - networkx >=2.1
    - sqlalchemy
    - click
    - click-plugins
    - bel-resources
    - requests
    - requests-file
    - pyparsing
    - tqdm

test:
  # Python imports
  imports:
    - pybel
  commands:
    - pybel --help

about:
  home: https://github.com/pybel/pybel
  license: Apache Software License
  license_file: LICENSE
  summary: 'PyBEL is a Python package for parsing and handling biological networks encoded in the Biological Expression Language (BEL)'

extra:
  container:
    extended-base: true
