{% set name = 'beast2' %}
{% set version = '2.6.1' %}

package:
  name: '{{ name }}'
  version: '{{ version }}'

source:
  url: https://github.com/CompEvol/beast2/releases/download/v{{ version }}/BEAST.package.v{{ version }}.zip
  sha256: c5ebe42c0d327a3aec49cc94b6a2b53edd0ed90b932f5dbd88484ede0c8a4625
  patches:
    - beast_lib.patch

build:
  number: 0
  noarch: generic

requirements:
  build:
    - gettext

  host:
    - openjdk 8.0* zulu8*
    - beagle-lib
    - fontconfig
    - font-ttf-ubuntu
    - fontconfig
    - freetype
    - xorg-libxtst

  run:
    - openjdk 8.0* zulu8*
    - beagle-lib
    - fontconfig
    - font-ttf-ubuntu
    - fontconfig
    - freetype
    - xorg-libxtst

test:
  commands:
    - beast -version
    # check to make sure beagle-lib is loaded ok
    - beast -beagle_info \| grep Flags
    - applauncher -help
    - packagemanager -help
    - loganalyser -h
    - logcombiner -help
    - treeannotator -help

about:
  home: http://www.beast2.org
  license: LGPLv2.1
  license_file: LICENSE.txt
  summary: "BEAST 2 is a cross-platform program for Bayesian phylogenetic analysis of molecular sequences."
