package:
  name: perl-test-warnings
  version: "0.027"

source:
  url: https://cpan.metacpan.org/authors/id/E/ET/ETHER/Test-Warnings-0.027.tar.gz
  sha256: "118dd9f48408557555f0af5478e0e873f9df0952cf5911f697a4ce5165880864"

requirements:
  host:
    - perl
    - perl-cpan-meta-check

  run:
    - perl

build:
  number: 0

test:
  imports:
    - Test::Warnings

about:
  home: https://github.com/karenetheridge/Test-Warnings
  license: perl_5
  summary: 'Test for warnings and the lack of them'
