{% set name = "perl-module-corelist" %}
{% set version = "5.20190820" %}
{% set sha256 = "a3748a9142cc4ed1dda4b133801e2a6a4477eebd86b472848cb28bc911523d2a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/B/BI/BINGOS/Module-CoreList-5.20190820.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  host:
    - perl
    - perl-version
    - perl-extutils-makemaker

  run:
    - perl
    - perl-version

test:
  imports:
    - Module::CoreList
    - Module::CoreList::Utils

about:
  home: http://dev.perl.org/
  license: perl_5
  summary: 'what modules shipped with versions of perl'
