{% set name = "perl-module-corelist" %}
{% set version = "5.20190920" %}
{% set sha256 = "e7e2247d9381a4253bc48ee5d39da8b54cfeda618bd7095220d1269325c0c1fc" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/B/BI/BINGOS/Module-CoreList-5.20190920.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  host:
    - perl
    - perl-version
    - perl-extutils-makemaker

  run:
    - perl
    - perl-version

test:
  imports:
    - Module::CoreList
    - Module::CoreList::Utils

about:
  home: http://dev.perl.org/
  license: perl_5
  summary: 'what modules shipped with versions of perl'
