{% set name = "perl-term-detect-software" %}
{% set version = "0.222" %}
{% set sha256 = "5aa0223c66afa9996c719dbcc94374ace02cf45cfe6f877337e797f41f79a48c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/P/PE/PERLANCAR/Term-Detect-Software-0.222.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  host:
    - perl
    - perl-experimental
    - perl-perl-osnames >=0.09
    - perl-file-which
    - perl-extutils-makemaker

  run:
    - perl
    - perl-experimental
    - perl-file-which

test:
  imports:
    - Term::Detect::Software

about:
  home: https://metacpan.org/release/Term-Detect-Software
  license: perl_5
  summary: 'Detect terminal (emulator) software and its capabilities'
