{% set name = "iced" %}
{% set version = "0.5.1" %}
{% set sha256 = "cfd9532085b709ea43c8a9d96e8d4dbc27f46058530fb21f7efd91b4a4407b76" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: https://github.com/hiclib/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - numpy >=1.9
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=0.14
    - pandas
    - scikit-learn
    - cython
    - matplotlib

test:
  imports:
    - iced

about:
  home: https://github.com/hiclib/iced
  license: new BSD
  license_family: BSD
  license_file: COPYING
  summary: "The python module iced implements the ICE normalization of hic data."
