{% set name = "bel-resources" %}
{% set version = "0.0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "660d4972f3107b191f68e104adb437883d054508ec3a68c9238aa804c2f52329"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - requests
    - requests-file
    - multisplitby

about:
  home: "https://github.com/pybel/bel-resources/"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE"
  summary: "Utilities for BEL (Biological Expression Language) resource files"

extra:
  recipe-maintainers:
    - dpryan79
