{% set name = "pangolearn" %}
{% set version = "2021-04-23" %}


package:
  name: "{{ name|lower }}"
  version: "{{ version |replace("-", ".") }}"

source:
  url: https://github.com/cov-lineages/pangoLEARN/archive/{{ version }}.tar.gz
  sha256: 174fa8dd067fd1fe09638b323c49d9eba8c3d3fd07967a65d11890794a7289c3

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed . 
  noarch: python

requirements:
  host:
    - pip
    - python

  run:
    - python

test:
  imports:
    - pangoLEARN

about:
  home: https://github.com/cov-lineages/pangoLEARN
  license: GPL-3.0
  license_family: GPL3
  summary: Store of the trained model for pangolin to access.
