{% set name = "perl-specio" %}
{% set version = "0.44" %}
{% set sha256 = "b544177c4577b3d0dfbc4e1f695678714eefd7f40399da6b7a7d123e317b6d6f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/Specio-0.44.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  host:
    - perl
    - perl-extutils-makemaker
    - perl-lib
    - perl-try-tiny
    - perl-role-tiny
    - perl-parent
    - perl-devel-stacktrace
    - perl-version
    - perl-eval-closure
    - perl-carp
    - perl-sub-quote
    - perl-mro-compat
    - perl-storable
    - perl-test-needs
    - perl-module-runtime
    - perl-exporter
    - perl-test-fatal

  run:
    - perl
    - perl-storable
    - perl-try-tiny
    - perl-role-tiny
    - perl-parent
    - perl-devel-stacktrace
    - perl-exporter
    - perl-version
    - perl-module-runtime
    - perl-eval-closure
    - perl-carp
    - perl-sub-quote
    - perl-mro-compat
    - perl-test-fatal

test:
  imports:
    - Specio
    - Specio::Coercion
    - Specio::Constraint::AnyCan
    - Specio::Constraint::AnyDoes
    - Specio::Constraint::AnyIsa
    - Specio::Constraint::Enum
    - Specio::Constraint::Intersection
    - Specio::Constraint::ObjectCan
    - Specio::Constraint::ObjectDoes
    - Specio::Constraint::ObjectIsa
    - Specio::Constraint::Parameterizable
    - Specio::Constraint::Parameterized
    - Specio::Constraint::Role::CanType
    - Specio::Constraint::Role::DoesType
    - Specio::Constraint::Role::Interface
    - Specio::Constraint::Role::IsaType
    - Specio::Constraint::Simple
    - Specio::Constraint::Structurable
    - Specio::Constraint::Structured
    - Specio::Constraint::Union
    - Specio::Declare
    - Specio::DeclaredAt
    - Specio::Exception
    - Specio::Exporter
    - Specio::Helpers
    - Specio::Library::Builtins
    - Specio::Library::Numeric
    - Specio::Library::Perl
    - Specio::Library::String
    - Specio::Library::Structured
    - Specio::Library::Structured::Dict
    - Specio::Library::Structured::Map
    - Specio::Library::Structured::Tuple
    - Specio::OO
    - Specio::PartialDump
    - Specio::Registry
    - Specio::Role::Inlinable
    - Specio::Subs
    - Specio::TypeChecks

about:
  home: http://metacpan.org/release/Specio
  license: artistic_2
  summary: 'Type constraints and coercions for Perl'

