package:
  name: perl-error
  version: "0.17028"

source:
  url: https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/Error-0.17028.tar.gz
  sha256: 3ad85c5e58b31c8903006298424a51bba39f1840e324f5ae612eabc8b935e960

build:
  number: 0

requirements:
  host:
    - perl
    - perl-module-build

  run:
    - perl

test:
  # Perl 'use' tests
  imports:
    - Error
    - Error::Simple

about:
  home: http://metacpan.org/pod/Error
  license: perl_5
  summary: 'Error/exception handling in an OO-ish way'
